### ISSUE TITLE
Lockdropped at 2nd eth lockdrop. Can't see PLM in my wallet.

### ISSUE THREAD

**Issue by kyoungrok0517** [PlasmNetwork/lockdrop-ui#159]
![image](https://user-images.githubusercontent.com/1051900/113407423-3670f400-93e8-11eb-8e7b-d5039498e574.png)

![image](https://user-images.githubusercontent.com/1051900/113407456-4ab4f100-93e8-11eb-8778-2dc4e49c3585.png)

Hello. I participated in 2nd eth lockdrop, and successfully received PLM tokens at that time. Until today I did nothing. Today I re-opened my Plasm wallet and can't see my tokens. I need help to solve this.

---

Claim ID: 0x6ed8b3f5dc1abed21b28f66f2c30004f6613759c2aa343570a482fb587bd0352
Sending to WPDRwyMdzZrroQPni3bZfqzTzeJPZyc85Ba8pR8M17uERpM

**Comment by hoonsubin** [comment]
Thank you for reporting this issue. I have checked your address and the lockdrop extrinsic event has successfully sent your funds, according to the block history.
![bandicam 2021-04-02 19-36-07-202](https://user-images.githubusercontent.com/40356749/113408799-ffe8a880-93ea-11eb-9ef7-b2ca1289b68f.jpg)
![bandicam 2021-04-02 19-37-25-874](https://user-images.githubusercontent.com/40356749/113408811-02e39900-93eb-11eb-8e22-7ac1d011d692.jpg)

The amount that your `PLASM (EXTENSION)` account owns is correct. The difference in token number display could be a UI glitch due to different decimal points used on Polkadot-js/api and our chain. (PLM is 15 decimal points while most other chains are 18 decimal points).

You can find more info about your address and the lock event from the following links:
- address: <https://plasm.subscan.io/account/WPDRwyMdzZrroQPni3bZfqzTzeJPZyc85Ba8pR8M17uERpM>
- lock claim event: <https://plasm.subscan.io/extrinsic/1269278-1>

**Comment by kyoungrok0517** [comment]
Strange to see the number is almost doubled. Thanks for the support!
